### ISSUE TITLE
[Bug]: Player values are wonky

### ISSUE THREAD

**Issue by Garcello822** [wwosimulation/tracker#353]
### What happened?

When you try to remove certain items, the numbers are wrong like when i tried to remove 5 single roses (rose) from somebody with 21, it said that i couldn't remove more than they had. You also can't remove one gem if they have one gem. Please make 0 a valid number as well for value

### What part of the bot are you seeing the problem on?

Economy

**Comment by Hackante** [comment]
You will always be able to remove 1 gem if someone has one gem with the option `force`/-f. 
But I think the problem is somewhere else. So that it thinks that you try to remove more that you actually do. 

Could you also tell us if this happened in the message or slash command?
This is important as we have both supported for this interaction with the bot.

It would also be helpful if you could state the whole command you used or at least the time so we can search for it in the logs


Thank you in advance

**Comment by Garcello822** [comment]
The response message told me I could not take more then they had (I was using slash). 
Slash looked like as follows:
/Player [tomato ketchup] rose remove 5.
It gave me the message even though I had 21
